using System.Collections.Generic;
using System.IO;
using System.Text;
using SolutionDeploymentAdvisor.Models;

namespace SolutionDeploymentAdvisor.Services
{
    /// <summary>Exports analysis results to CSV or PAC CLI script.</summary>
    public static class ExportService
    {
        /// <summary>Generates a CSV string from the component list — all columns matching the grid.</summary>
        public static string ToCsv(List<ComponentInfo> components)
        {
            var sb = new StringBuilder();
            sb.AppendLine("ComponentId,Name,TypeCode,TypeLabel,Lifecycle,Category,Risk,SourceVersion,TargetVersion,MissingPatches,LastTargetPatch,Note");
            foreach (var c in components)
            {
                sb.AppendLine(
                    $"\"{Escape(c.ComponentId.ToString())}\"," +
                    $"\"{Escape(c.Name)}\"," +
                    $"{c.ComponentType}," +
                    $"\"{Escape(ComponentNameResolver.TypeLabel(c.ComponentType))}\"," +
                    $"{c.Lifecycle}," +
                    $"{c.Category}," +
                    $"{c.Risk}," +
                    $"\"{Escape(c.SourceVersionDetails ?? string.Empty)}\"," +
                    $"\"{Escape(c.TargetVersionDetails ?? string.Empty)}\"," +
                    $"\"{Escape(c.MissingPatches ?? string.Empty)}\"," +
                    $"\"{Escape(c.LastTargetSolutionName ?? string.Empty)}\"," +
                    $"\"{Escape(c.RiskReason ?? string.Empty)}\"");
            }
            return sb.ToString();
        }

        /// <summary>Generates a PAC CLI shell script to add components to a solution.</summary>
        public static string ToPacCli(List<ComponentInfo> components, string solutionUniqueName)
        {
            var sb = new StringBuilder();
            sb.AppendLine("#!/bin/bash");
            sb.AppendLine($"# PAC CLI – add components to solution: {solutionUniqueName}");
            sb.AppendLine("# Generated by Solution Deployment Advisor");
            sb.AppendLine();
            sb.AppendLine($"pac solution add-component --solution-name \"{solutionUniqueName}\" \\");
            foreach (var c in components)
            {
                sb.AppendLine($"  # {c.Name} ({ComponentNameResolver.TypeLabel(c.ComponentType)})");
                sb.AppendLine($"  # pac solution add-component --solution \"{solutionUniqueName}\" --component {c.ComponentId} --component-type {c.ComponentType}");
            }
            return sb.ToString();
        }

        public static void SaveToFile(string content, string path)
            => File.WriteAllText(path, content, Encoding.UTF8);

        private static string Escape(string s) => s.Replace("\"", "\"\"").Replace("\r", "").Replace("\n", " | ");
    }
}
